services:
  - type: web
    name: realtorone-backend
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: false # User will provide this or Render will ask
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: realtorone-backend
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: realtorone-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: realtorone-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: realtorone-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: realtorone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: realtorone-db
          property: password

databases:
  - name: realtorone-db
    plan: free
    region: ohio
